# Generated by Django 3.1.5 on 2021-03-15 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False, 'verbose_name': '프로파일'},
        ),
    ]
