# Generated by Django 3.1.5 on 2021-02-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0006_auto_20210201_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='createDate',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updateDate',
        ),
    ]
